{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "API HORUS ALUNOS",
    "description": "Documentação API HORUS ALUNOS "
  },
  "host": "localhost:3000",
  "basePath": "",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/aluno": {
      "get": {
        "tags": [
          "Alunos"
        ],
        "summary": "Consulta lista de Alunos",
        "description": "Consulta lista de Alunos, todos os Alunos cadastrados",
        "responses": {
          "200": {
            "description": "Sucesso!",
            "schema": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "number",
                  "example": 1
                },
                "alunos": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "number",
                        "example": 1
                      },
                      "nome": {
                        "type": "string",
                        "example": "Cristian"
                      },
                      "sobrenome": {
                        "type": "string",
                        "example": "Mila"
                      },
                      "periodo": {
                        "type": "number",
                        "example": 4
                      },
                      "obsrevacao": {
                        "type": "string",
                        "example": "TaldoTeste"
                      }
                    }
                  }
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "post": {
        "tags": [
          "Alunos"
        ],
        "description": "",
        "parameters": [
          {
            "name": "json",
            "in": "body",
            "description": "Dados para inserir um novo aluno!",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number",
                  "example": 1
                },
                "nome": {
                  "type": "string",
                  "example": "Crisdo"
                },
                "sobrenome": {
                  "type": "string",
                  "example": "Test"
                },
                "periodo": {
                  "type": "number",
                  "example": 5
                },
                "observador": {
                  "type": "string",
                  "example": "Pai ta ON"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Campo Faltando!"
                },
                "detalhe": {
                  "type": "string",
                  "example": "Os campos nome e periodo são obrigatórios"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    },
    "/aluno/{id}": {
      "delete": {
        "tags": [
          "Alunos"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "put": {
        "tags": [
          "Alunos"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      },
      "patch": {
        "tags": [
          "Alunos"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Nenhum Conteúdo"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    }
  }
}